name: Matugr Github Actions CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source
      uses: actions/checkout@v2
    
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
  
    - name: Build Library
      uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
      with:
        arguments: :matugr:assemble
        
    - name: Build Sample App
      uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
      with:
        arguments: :app:assemble
        
    - name: Library Unit Tests
      uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
      with:
        arguments: :matugr:jacocoTestReport

#    - name: generate report
#      uses: actions/upload-artifact@v4
#      with:
#        name: report
#        path: matugr/build/reports/jacoco/jacocoTestReport
#
#    - name: Download Test Reports Folder
#      uses: actions/download-artifact@v4
#      with:
#        name: report
#        path: matugr/build/reports/jacoco/jacocoTestReport

    - name: Upload Test Report
      uses: codecov/codecov-action@v3
      with:
        files: "matugr/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml"
